plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

sStyle/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec:
  Language:
    Include:
      - 'spec/**/*_spec.rb'
RSpec/MultipleExpectations:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false
RSpec/ExampleLength:
  Enabled: true
  Max: 100

RSpec/MessageSpies:
  Enabled: false
